/*
 * 14.cpp
 *
 * Dynamic Boolean truth-arithmetic acceptance engine for Book Sport tables
 * generated by 13.cpp.
 *
 * Purpose:
 *   - Load the static formal Book Sport table emitted by 13.cpp.
 *   - Treat row headings and column headings as pointers to instructional
 *     semantic structures.
 *   - Recompute and verify pointer hashes, semantic hashes, and cell identity
 *     hashes before evaluation.
 *   - Dynamically evaluate Boolean acceptance contracts.
 *   - Enforce hard barriers: a cell remains closed unless its selected Boolean
 *     expression evaluates to true.
 *   - Emit escaped, replayable, information-identity-preserving acceptance
 *     event records for downstream engineering architecture workflows.
 *
 * Build:
 *   c++ -std=c++17 -Wall -Wextra -pedantic -O2 14.cpp -o 14
 *
 * Examples:
 *   ./14 --table engineering_architecture_book_sport.table.txt
 *   ./14 --table engineering_architecture_book_sport.table.txt \
 *        --rules book_sport_14.rules \
 *        --facts book_sport_14.facts \
 *        --execute --overwrite --all \
 *        --output-target book_sport_14.acceptance.events.txt
 *
 * Rule examples:
 *   default=false
 *   column:observe=integrity_ok AND semantic_present
 *   x_measurement.validate=integrity_ok AND semantic_present AND measurement_verified
 *   x_boundary->barrier_check=integrity_ok AND hard_barrier AND operator_authorized
 *   cell:51c2faea9bd8ce7c=integrity_ok AND measurement_verified
 *
 * Boolean expression grammar:
 *   literals: true false 1 0 yes no on off
 *   unary:    NOT a, !a
 *   binary:   a AND b, a && b, a & b
 *             a NAND b
 *             a OR b,  a || b, a | b
 *             a NOR b
 *             a XOR b, a ^ b
 *             a XNOR b, a EQV b, a EQUIV b
 *             a IMPLY b, a -> b
 *   grouping: ( ... )
 *
 * Built-in variables per cell include:
 *   integrity_ok, row_hash_ok, column_hash_ok, row_semantic_hash_ok,
 *   column_semantic_hash_ok, cell_identity_ok, semantic_present,
 *   row_semantic_present, column_semantic_present, hard_barrier,
 *   boolean_engine_is_14, contract_present, barrier_policy_known,
 *   row__<sanitized_row_pointer>, column__<sanitized_column_pointer>.
 */

#include <algorithm>
#include <cctype>
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <map>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

namespace {

constexpr std::uint64_t kDefaultLimit = 10000;
constexpr std::uint64_t kUnapprovedRecordLimit = 100000;
constexpr std::size_t kMaxLineLength = 1024 * 1024;
constexpr std::size_t kMaxExpressionLength = 16384;

struct Options {
    bool execute = false;
    bool overwrite = false;
    bool allow_large = false;
    bool all = false;
    bool strict = true;
    bool accepted_only = false;
    bool rejected_only = false;
    bool explain = false;
    std::uint64_t start = 0;
    std::uint64_t limit = kDefaultLimit;
    std::string table_path;
    std::string output_target = "book_sport_14.acceptance.events.txt";
    std::string rules_path;
    std::string facts_path;
    std::string sample_rules_path;
    std::string sample_facts_path;
};

struct Rule {
    std::string selector;
    std::string expression;
    std::uint64_t order = 0;
};

struct RowRecord {
    std::uint64_t index = 0;
    std::string pointer;
    std::string pointer_hash;
    std::string semantic_hash;
    std::string role;
    std::string semantic;
};

struct ColumnRecord {
    std::uint64_t index = 0;
    std::string pointer;
    std::string pointer_hash;
    std::string semantic_hash;
    std::string role;
    std::string semantic;
};

struct CellRecord {
    std::uint64_t ordinal = 0;
    std::uint64_t row_index = 0;
    std::uint64_t column_index = 0;
    std::string row_pointer;
    std::string column_pointer;
    std::string cell_pointer;
    std::string row_semantic_hash;
    std::string column_semantic_hash;
    std::string cell_identity_hash;
    std::string acceptance_state;
    std::string barrier_policy;
    std::string boolean_engine;
    std::string boolean_contract;
    std::string row_semantic;
    std::string column_semantic;
};

struct TableSource {
    std::map<std::string, std::string> metadata;
    std::vector<RowRecord> rows;
    std::vector<ColumnRecord> columns;
    std::vector<CellRecord> cells;
    std::map<std::uint64_t, RowRecord> rows_by_index;
    std::map<std::uint64_t, ColumnRecord> columns_by_index;
    std::map<std::string, RowRecord> rows_by_pointer;
    std::map<std::string, ColumnRecord> columns_by_pointer;
};

struct IntegrityReport {
    bool row_known = false;
    bool column_known = false;
    bool row_pointer_matches = false;
    bool column_pointer_matches = false;
    bool row_hash_ok = false;
    bool column_hash_ok = false;
    bool row_semantic_hash_ok = false;
    bool column_semantic_hash_ok = false;
    bool cell_identity_ok = false;
    bool integrity_ok = false;
    std::string expected_cell_identity_hash;
};

struct Decision {
    const CellRecord* cell = nullptr;
    IntegrityReport integrity;
    Rule selected_rule;
    int selector_rank = 0;
    bool expression_result = false;
    bool accepted = false;
    std::string expression_hash;
    std::string event_hash;
    std::string accepted_information;
};

class OutputSink {
public:
    virtual ~OutputSink() = default;
    virtual void write(std::string_view value) = 0;
};

class StreamSink final : public OutputSink {
public:
    explicit StreamSink(std::ostream& stream) : stream_(stream) {}

    void write(std::string_view value) override {
        stream_.write(value.data(), static_cast<std::streamsize>(value.size()));
        if (!stream_) {
            throw std::runtime_error("Failed while writing to stream.");
        }
    }

private:
    std::ostream& stream_;
};

class FileSink final : public OutputSink {
public:
    FileSink(const std::string& path, const char* mode) : file_(std::fopen(path.c_str(), mode)) {
        if (file_ == nullptr) {
            throw std::runtime_error("Unable to open output file: " + path);
        }
    }

    ~FileSink() override {
        if (file_ != nullptr) {
            std::fclose(file_);
        }
    }

    FileSink(const FileSink&) = delete;
    FileSink& operator=(const FileSink&) = delete;

    void write(std::string_view value) override {
        if (!value.empty() &&
            std::fwrite(value.data(), 1, value.size(), file_) != value.size()) {
            throw std::runtime_error("Failed while writing output file.");
        }
    }

private:
    std::FILE* file_;
};

class Writer {
public:
    explicit Writer(OutputSink& sink) : sink_(sink) {}

    Writer& operator<<(char value) {
        sink_.write(std::string_view(&value, 1));
        return *this;
    }

    Writer& operator<<(std::string_view value) {
        sink_.write(value);
        return *this;
    }

    Writer& operator<<(const std::string& value) {
        sink_.write(value);
        return *this;
    }

    Writer& operator<<(const char* value) {
        sink_.write(value == nullptr ? std::string_view{} : std::string_view(value));
        return *this;
    }

    template <typename T>
    Writer& operator<<(const T& value) {
        std::ostringstream out;
        out << value;
        sink_.write(out.str());
        return *this;
    }

private:
    OutputSink& sink_;
};

class InputFile {
public:
    explicit InputFile(const std::string& path) : file_(std::fopen(path.c_str(), "rb")) {
        if (file_ == nullptr) {
            throw std::runtime_error("Unable to open input file: " + path);
        }
    }

    ~InputFile() {
        if (file_ != nullptr) {
            std::fclose(file_);
        }
    }

    InputFile(const InputFile&) = delete;
    InputFile& operator=(const InputFile&) = delete;

    bool read_line(std::string& line) {
        line.clear();
        char buffer[8192];

        for (;;) {
            if (std::fgets(buffer, sizeof(buffer), file_) == nullptr) {
                if (std::ferror(file_) != 0) {
                    throw std::runtime_error("Failed while reading input file.");
                }
                return !line.empty();
            }

            line += buffer;
            if (line.size() > kMaxLineLength) {
                throw std::runtime_error("Input line exceeds maximum supported length.");
            }

            if (!line.empty() && line.back() == '\n') {
                break;
            }

            const std::size_t chunk_size = std::char_traits<char>::length(buffer);
            if (chunk_size + 1 < sizeof(buffer)) {
                break;
            }
        }

        while (!line.empty() && (line.back() == '\n' || line.back() == '\r')) {
            line.pop_back();
        }

        return true;
    }

private:
    std::FILE* file_;
};

std::string to_lower(std::string value) {
    for (char& c : value) {
        c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    }
    return value;
}

std::string trim(std::string value) {
    while (!value.empty() && std::isspace(static_cast<unsigned char>(value.front()))) {
        value.erase(value.begin());
    }
    while (!value.empty() && std::isspace(static_cast<unsigned char>(value.back()))) {
        value.pop_back();
    }
    return value;
}

bool equals_ignore_case(std::string_view lhs, std::string_view rhs) {
    if (lhs.size() != rhs.size()) {
        return false;
    }
    for (std::size_t i = 0; i < lhs.size(); ++i) {
        if (std::tolower(static_cast<unsigned char>(lhs[i])) !=
            std::tolower(static_cast<unsigned char>(rhs[i]))) {
            return false;
        }
    }
    return true;
}

bool file_exists(const std::string& path) {
    std::FILE* file = std::fopen(path.c_str(), "rb");
    if (file == nullptr) {
        return false;
    }
    std::fclose(file);
    return true;
}

bool parse_u64(std::string_view text, std::uint64_t& out) {
    if (text.empty()) {
        return false;
    }
    std::uint64_t value = 0;
    for (char c : text) {
        if (!std::isdigit(static_cast<unsigned char>(c))) {
            return false;
        }
        const std::uint64_t digit = static_cast<std::uint64_t>(c - '0');
        if (value > (std::numeric_limits<std::uint64_t>::max() - digit) / 10) {
            return false;
        }
        value = value * 10 + digit;
    }
    out = value;
    return true;
}

std::uint64_t require_u64_arg(const std::vector<std::string>& args, std::size_t& i) {
    if (i + 1 >= args.size()) {
        throw std::runtime_error("Missing value for " + args[i]);
    }
    std::uint64_t value = 0;
    if (!parse_u64(args[++i], value)) {
        throw std::runtime_error("Invalid unsigned integer for " + args[i - 1] + ": " + args[i]);
    }
    return value;
}

std::string require_string_arg(const std::vector<std::string>& args, std::size_t& i) {
    if (i + 1 >= args.size()) {
        throw std::runtime_error("Missing value for " + args[i]);
    }
    return args[++i];
}

std::string unescape_text(std::string_view value) {
    std::string out;
    out.reserve(value.size());

    for (std::size_t i = 0; i < value.size(); ++i) {
        char c = value[i];
        if (c != '\\' || i + 1 >= value.size()) {
            out.push_back(c);
            continue;
        }

        const char next = value[++i];
        if (next == 'n') {
            out.push_back('\n');
        } else if (next == 't') {
            out.push_back('\t');
        } else if (next == 'r') {
            out.push_back('\r');
        } else if (next == '\\') {
            out.push_back('\\');
        } else if (next == 'x' && i + 2 < value.size()) {
            const char h1 = value[i + 1];
            const char h2 = value[i + 2];
            auto hex_value = [](char h) -> int {
                if (h >= '0' && h <= '9') return h - '0';
                if (h >= 'a' && h <= 'f') return 10 + h - 'a';
                if (h >= 'A' && h <= 'F') return 10 + h - 'A';
                return -1;
            };
            const int v1 = hex_value(h1);
            const int v2 = hex_value(h2);
            if (v1 >= 0 && v2 >= 0) {
                out.push_back(static_cast<char>(v1 * 16 + v2));
                i += 2;
            } else {
                out.push_back(next);
            }
        } else {
            out.push_back(next);
        }
    }

    return out;
}

std::string escape_field(std::string_view value) {
    std::ostringstream out;
    out << std::hex << std::uppercase << std::setfill('0');

    for (unsigned char c : value) {
        if (c == '\\') {
            out << "\\\\";
        } else if (c == '\n') {
            out << "\\n";
        } else if (c == '\r') {
            out << "\\r";
        } else if (c == '\t') {
            out << "\\t";
        } else if (c < 32 || c == 127) {
            out << "\\x" << std::setw(2) << static_cast<unsigned int>(c);
        } else {
            out << static_cast<char>(c);
        }
    }

    return out.str();
}

std::vector<std::string> split_tab_line(const std::string& line) {
    std::vector<std::string> parts;
    std::string current;
    for (char c : line) {
        if (c == '\t') {
            parts.push_back(current);
            current.clear();
        } else {
            current.push_back(c);
        }
    }
    parts.push_back(current);
    return parts;
}

std::uint64_t fnv1a_64(std::string_view value) {
    std::uint64_t hash = 14695981039346656037ull;
    for (unsigned char c : value) {
        hash ^= static_cast<std::uint64_t>(c);
        hash *= 1099511628211ull;
    }
    return hash;
}

std::string hex64(std::uint64_t value) {
    std::ostringstream out;
    out << std::hex << std::nouppercase << std::setfill('0') << std::setw(16) << value;
    return out.str();
}

std::string sanitize_identifier(std::string_view value) {
    std::string out;
    out.reserve(value.size());
    for (unsigned char c : value) {
        if (std::isalnum(c)) {
            out.push_back(static_cast<char>(std::tolower(c)));
        } else {
            out.push_back('_');
        }
    }
    while (out.find("__") != std::string::npos) {
        const std::size_t pos = out.find("__");
        out.replace(pos, 2, "_");
    }
    if (!out.empty() && out.front() == '_') {
        out.erase(out.begin());
    }
    if (!out.empty() && out.back() == '_') {
        out.pop_back();
    }
    if (out.empty()) {
        return "empty";
    }
    return out;
}

bool parse_bool_value(std::string_view raw, bool& out) {
    const std::string value = to_lower(trim(std::string(raw)));
    if (value == "true" || value == "1" || value == "yes" || value == "on" || value == "accept" || value == "accepted") {
        out = true;
        return true;
    }
    if (value == "false" || value == "0" || value == "no" || value == "off" || value == "reject" || value == "rejected") {
        out = false;
        return true;
    }
    return false;
}

std::pair<std::string, std::string> split_assignment(const std::string& raw) {
    const std::size_t arrow = raw.find("=>");
    if (arrow != std::string::npos) {
        return {trim(raw.substr(0, arrow)), trim(raw.substr(arrow + 2))};
    }
    const std::size_t equals = raw.find('=');
    if (equals != std::string::npos) {
        return {trim(raw.substr(0, equals)), trim(raw.substr(equals + 1))};
    }
    throw std::runtime_error("Expected assignment using = or =>: " + raw);
}

std::string metadata_value(const TableSource& table, const std::string& key, const std::string& fallback = "") {
    const auto found = table.metadata.find(key);
    if (found == table.metadata.end()) {
        return fallback;
    }
    return found->second;
}

std::string make_cell_identity_material(const TableSource& table, const CellRecord& cell) {
    const char sep = static_cast<char>(0x1F);
    std::ostringstream out;
    out << "13.cpp" << sep
        << metadata_value(table, "table_name") << sep
        << cell.ordinal << sep
        << cell.row_index << sep
        << cell.column_index << sep
        << cell.row_pointer << sep
        << cell.column_pointer << sep
        << cell.row_semantic << sep
        << cell.column_semantic << sep
        << cell.cell_pointer << sep
        << cell.boolean_engine << sep
        << cell.boolean_contract << sep
        << cell.barrier_policy << sep
        << cell.acceptance_state;
    return out.str();
}

void parse_metadata_line(TableSource& table, const std::string& line) {
    std::string raw = line;
    if (!raw.empty() && raw[0] == '#') {
        raw.erase(raw.begin());
    }
    raw = trim(raw);
    if (raw.empty()) {
        return;
    }
    const std::size_t equals = raw.find('=');
    if (equals == std::string::npos) {
        return;
    }
    const std::string key = trim(raw.substr(0, equals));
    const std::string value = unescape_text(trim(raw.substr(equals + 1)));
    if (!key.empty()) {
        table.metadata[key] = value;
    }
}

RowRecord parse_row_record(const std::vector<std::string>& parts) {
    if (parts.size() != 7) {
        throw std::runtime_error("Invalid row record field count; expected 7.");
    }
    RowRecord row;
    if (!parse_u64(parts[1], row.index)) {
        throw std::runtime_error("Invalid row index: " + parts[1]);
    }
    row.pointer = unescape_text(parts[2]);
    row.pointer_hash = unescape_text(parts[3]);
    row.semantic_hash = unescape_text(parts[4]);
    row.role = unescape_text(parts[5]);
    row.semantic = unescape_text(parts[6]);
    return row;
}

ColumnRecord parse_column_record(const std::vector<std::string>& parts) {
    if (parts.size() != 7) {
        throw std::runtime_error("Invalid column record field count; expected 7.");
    }
    ColumnRecord column;
    if (!parse_u64(parts[1], column.index)) {
        throw std::runtime_error("Invalid column index: " + parts[1]);
    }
    column.pointer = unescape_text(parts[2]);
    column.pointer_hash = unescape_text(parts[3]);
    column.semantic_hash = unescape_text(parts[4]);
    column.role = unescape_text(parts[5]);
    column.semantic = unescape_text(parts[6]);
    return column;
}

CellRecord parse_cell_record(const std::vector<std::string>& parts) {
    if (parts.size() != 16) {
        throw std::runtime_error("Invalid cell record field count; expected 16.");
    }
    CellRecord cell;
    if (!parse_u64(parts[1], cell.ordinal)) {
        throw std::runtime_error("Invalid cell ordinal: " + parts[1]);
    }
    if (!parse_u64(parts[2], cell.row_index)) {
        throw std::runtime_error("Invalid cell row index: " + parts[2]);
    }
    if (!parse_u64(parts[3], cell.column_index)) {
        throw std::runtime_error("Invalid cell column index: " + parts[3]);
    }
    cell.row_pointer = unescape_text(parts[4]);
    cell.column_pointer = unescape_text(parts[5]);
    cell.cell_pointer = unescape_text(parts[6]);
    cell.row_semantic_hash = unescape_text(parts[7]);
    cell.column_semantic_hash = unescape_text(parts[8]);
    cell.cell_identity_hash = unescape_text(parts[9]);
    cell.acceptance_state = unescape_text(parts[10]);
    cell.barrier_policy = unescape_text(parts[11]);
    cell.boolean_engine = unescape_text(parts[12]);
    cell.boolean_contract = unescape_text(parts[13]);
    cell.row_semantic = unescape_text(parts[14]);
    cell.column_semantic = unescape_text(parts[15]);
    return cell;
}

void index_table(TableSource& table) {
    table.rows_by_index.clear();
    table.columns_by_index.clear();
    table.rows_by_pointer.clear();
    table.columns_by_pointer.clear();

    for (const RowRecord& row : table.rows) {
        if (!table.rows_by_index.emplace(row.index, row).second) {
            throw std::runtime_error("Duplicate row index: " + std::to_string(row.index));
        }
        if (!table.rows_by_pointer.emplace(row.pointer, row).second) {
            throw std::runtime_error("Duplicate row pointer: " + row.pointer);
        }
    }

    for (const ColumnRecord& column : table.columns) {
        if (!table.columns_by_index.emplace(column.index, column).second) {
            throw std::runtime_error("Duplicate column index: " + std::to_string(column.index));
        }
        if (!table.columns_by_pointer.emplace(column.pointer, column).second) {
            throw std::runtime_error("Duplicate column pointer: " + column.pointer);
        }
    }
}

TableSource load_table_source(const std::string& path) {
    InputFile in(path);
    TableSource table;
    std::string line;
    std::uint64_t line_number = 0;

    while (in.read_line(line)) {
        ++line_number;
        if (trim(line).empty()) {
            continue;
        }

        try {
            if (!line.empty() && line[0] == '#') {
                parse_metadata_line(table, line);
                continue;
            }

            const std::vector<std::string> parts = split_tab_line(line);
            if (parts.empty()) {
                continue;
            }

            if (parts[0] == "row") {
                table.rows.push_back(parse_row_record(parts));
            } else if (parts[0] == "column") {
                table.columns.push_back(parse_column_record(parts));
            } else if (parts[0] == "cell") {
                table.cells.push_back(parse_cell_record(parts));
            } else {
                throw std::runtime_error("Unknown table record type: " + parts[0]);
            }
        } catch (const std::exception& ex) {
            std::ostringstream message;
            message << "Table parse error at line " << line_number << ": " << ex.what();
            throw std::runtime_error(message.str());
        }
    }

    if (table.rows.empty()) {
        throw std::runtime_error("Table source contains no row records.");
    }
    if (table.columns.empty()) {
        throw std::runtime_error("Table source contains no column records.");
    }
    if (table.cells.empty()) {
        throw std::runtime_error("Table source contains no cell records.");
    }

    index_table(table);
    return table;
}

IntegrityReport verify_cell(const TableSource& table, const CellRecord& cell) {
    IntegrityReport report;
    const auto row_found = table.rows_by_index.find(cell.row_index);
    const auto column_found = table.columns_by_index.find(cell.column_index);
    report.row_known = row_found != table.rows_by_index.end();
    report.column_known = column_found != table.columns_by_index.end();

    if (report.row_known) {
        const RowRecord& row = row_found->second;
        report.row_pointer_matches = row.pointer == cell.row_pointer;
        report.row_hash_ok = row.pointer_hash == hex64(fnv1a_64(row.pointer));
        report.row_semantic_hash_ok = row.semantic_hash == hex64(fnv1a_64(row.semantic)) &&
                                      cell.row_semantic_hash == hex64(fnv1a_64(cell.row_semantic)) &&
                                      row.semantic == cell.row_semantic;
    }

    if (report.column_known) {
        const ColumnRecord& column = column_found->second;
        report.column_pointer_matches = column.pointer == cell.column_pointer;
        report.column_hash_ok = column.pointer_hash == hex64(fnv1a_64(column.pointer));
        report.column_semantic_hash_ok = column.semantic_hash == hex64(fnv1a_64(column.semantic)) &&
                                         cell.column_semantic_hash == hex64(fnv1a_64(cell.column_semantic)) &&
                                         column.semantic == cell.column_semantic;
    }

    report.expected_cell_identity_hash = hex64(fnv1a_64(make_cell_identity_material(table, cell)));
    report.cell_identity_ok = cell.cell_identity_hash == report.expected_cell_identity_hash;
    report.integrity_ok = report.row_known &&
                          report.column_known &&
                          report.row_pointer_matches &&
                          report.column_pointer_matches &&
                          report.row_hash_ok &&
                          report.column_hash_ok &&
                          report.row_semantic_hash_ok &&
                          report.column_semantic_hash_ok &&
                          report.cell_identity_ok;
    return report;
}

enum class TokenKind {
    end,
    ident,
    literal,
    op,
    lparen,
    rparen
};

struct Token {
    TokenKind kind = TokenKind::end;
    std::string text;
    bool literal = false;
};

std::vector<Token> tokenize_expression(const std::string& expression) {
    std::vector<Token> tokens;
    std::size_t i = 0;

    while (i < expression.size()) {
        const unsigned char c = static_cast<unsigned char>(expression[i]);
        if (std::isspace(c)) {
            ++i;
            continue;
        }

        if (expression[i] == '(') {
            tokens.push_back({TokenKind::lparen, "(", false});
            ++i;
            continue;
        }
        if (expression[i] == ')') {
            tokens.push_back({TokenKind::rparen, ")", false});
            ++i;
            continue;
        }

        if (i + 1 < expression.size()) {
            const std::string two = expression.substr(i, 2);
            if (two == "&&" || two == "||" || two == "->") {
                tokens.push_back({TokenKind::op, two, false});
                i += 2;
                continue;
            }
        }

        if (expression[i] == '!' || expression[i] == '&' || expression[i] == '|' || expression[i] == '^') {
            tokens.push_back({TokenKind::op, std::string(1, expression[i]), false});
            ++i;
            continue;
        }

        std::string word;
        while (i < expression.size()) {
            const char ch = expression[i];
            if (std::isspace(static_cast<unsigned char>(ch)) || ch == '(' || ch == ')' ||
                ch == '!' || ch == '&' || ch == '|' || ch == '^') {
                break;
            }
            if (ch == '-' && i + 1 < expression.size() && expression[i + 1] == '>') {
                break;
            }
            word.push_back(ch);
            ++i;
        }

        if (word.empty()) {
            throw std::runtime_error("Cannot tokenize Boolean expression near: " + expression.substr(i));
        }

        const std::string normalized = to_lower(word);
        bool literal = false;
        if (parse_bool_value(normalized, literal)) {
            tokens.push_back({TokenKind::literal, normalized, literal});
        } else if (normalized == "and" || normalized == "or" || normalized == "xor" ||
                   normalized == "not" || normalized == "nand" || normalized == "nor" ||
                   normalized == "xnor" || normalized == "eqv" || normalized == "equiv" ||
                   normalized == "imply" || normalized == "implies") {
            tokens.push_back({TokenKind::op, normalized, false});
        } else {
            tokens.push_back({TokenKind::ident, word, false});
        }
    }

    tokens.push_back({TokenKind::end, "", false});
    return tokens;
}

class BoolExpressionParser {
public:
    BoolExpressionParser(std::string expression,
                         const std::map<std::string, bool>& variables)
        : expression_(std::move(expression)),
          variables_(variables),
          tokens_(tokenize_expression(expression_)) {}

    bool evaluate() {
        pos_ = 0;
        const bool result = parse_implication();
        if (current().kind != TokenKind::end) {
            throw std::runtime_error("Unexpected token in Boolean expression: " + current().text);
        }
        return result;
    }

private:
    const Token& current() const {
        return tokens_[pos_];
    }

    bool match_op(std::string_view op) {
        if (current().kind == TokenKind::op && equals_ignore_case(current().text, op)) {
            ++pos_;
            return true;
        }
        return false;
    }

    bool parse_implication() {
        bool lhs = parse_or_xor();
        while (current().kind == TokenKind::op &&
               (current().text == "->" || equals_ignore_case(current().text, "imply") ||
                equals_ignore_case(current().text, "implies"))) {
            ++pos_;
            const bool rhs = parse_implication();
            lhs = (!lhs) || rhs;
        }
        return lhs;
    }

    bool parse_or_xor() {
        bool lhs = parse_and();
        for (;;) {
            if (match_op("or") || match_op("||") || match_op("|")) {
                const bool rhs = parse_and();
                lhs = lhs || rhs;
            } else if (match_op("nor")) {
                const bool rhs = parse_and();
                lhs = !(lhs || rhs);
            } else if (match_op("xor") || match_op("^")) {
                const bool rhs = parse_and();
                lhs = lhs != rhs;
            } else if (match_op("xnor") || match_op("eqv") || match_op("equiv")) {
                const bool rhs = parse_and();
                lhs = lhs == rhs;
            } else {
                return lhs;
            }
        }
    }

    bool parse_and() {
        bool lhs = parse_unary();
        for (;;) {
            if (match_op("and") || match_op("&&") || match_op("&")) {
                const bool rhs = parse_unary();
                lhs = lhs && rhs;
            } else if (match_op("nand")) {
                const bool rhs = parse_unary();
                lhs = !(lhs && rhs);
            } else {
                return lhs;
            }
        }
    }

    bool parse_unary() {
        if (match_op("not") || match_op("!")) {
            return !parse_unary();
        }
        return parse_primary();
    }

    bool parse_primary() {
        if (current().kind == TokenKind::literal) {
            const bool value = current().literal;
            ++pos_;
            return value;
        }

        if (current().kind == TokenKind::ident) {
            const std::string name = current().text;
            ++pos_;
            const auto found = variables_.find(name);
            if (found != variables_.end()) {
                return found->second;
            }
            const auto lower_found = variables_.find(to_lower(name));
            if (lower_found != variables_.end()) {
                return lower_found->second;
            }
            return false;
        }

        if (current().kind == TokenKind::lparen) {
            ++pos_;
            const bool value = parse_implication();
            if (current().kind != TokenKind::rparen) {
                throw std::runtime_error("Expected ')' in Boolean expression.");
            }
            ++pos_;
            return value;
        }

        throw std::runtime_error("Expected Boolean literal, identifier, or '(' but found: " + current().text);
    }

    std::string expression_;
    const std::map<std::string, bool>& variables_;
    std::vector<Token> tokens_;
    std::size_t pos_ = 0;
};

std::map<std::string, bool> load_facts_file(const std::string& path) {
    std::map<std::string, bool> facts;
    if (path.empty()) {
        return facts;
    }
    InputFile in(path);
    std::string line;
    std::uint64_t line_number = 0;
    while (in.read_line(line)) {
        ++line_number;
        std::string raw = trim(line);
        if (raw.empty() || raw[0] == '#') {
            continue;
        }
        try {
            const auto assignment = split_assignment(raw);
            bool value = false;
            if (!parse_bool_value(assignment.second, value)) {
                throw std::runtime_error("Invalid Boolean value: " + assignment.second);
            }
            facts[assignment.first] = value;
            facts[to_lower(assignment.first)] = value;
        } catch (const std::exception& ex) {
            std::ostringstream message;
            message << "Facts file " << path << " line " << line_number << ": " << ex.what();
            throw std::runtime_error(message.str());
        }
    }
    return facts;
}

std::vector<Rule> load_rules_file(const std::string& path, std::uint64_t& next_order) {
    std::vector<Rule> rules;
    if (path.empty()) {
        return rules;
    }
    InputFile in(path);
    std::string line;
    std::uint64_t line_number = 0;
    while (in.read_line(line)) {
        ++line_number;
        std::string raw = trim(line);
        if (raw.empty() || raw[0] == '#') {
            continue;
        }
        try {
            const auto assignment = split_assignment(raw);
            if (assignment.first.empty()) {
                throw std::runtime_error("Empty rule selector.");
            }
            if (assignment.second.empty()) {
                throw std::runtime_error("Empty rule expression.");
            }
            if (assignment.second.size() > kMaxExpressionLength) {
                throw std::runtime_error("Rule expression exceeds maximum length.");
            }
            rules.push_back({assignment.first, assignment.second, next_order++});
        } catch (const std::exception& ex) {
            std::ostringstream message;
            message << "Rules file " << path << " line " << line_number << ": " << ex.what();
            throw std::runtime_error(message.str());
        }
    }
    return rules;
}

int selector_match_rank(const Rule& rule, const CellRecord& cell) {
    const std::string selector = trim(rule.selector);
    const std::string selector_lower = to_lower(selector);
    if (selector_lower == "default" || selector == "*") {
        return 1;
    }

    const std::string row_prefix = "row:";
    const std::string column_prefix = "column:";
    const std::string cell_prefix = "cell:";
    const std::string cell_pointer_prefix = "cell_pointer:";
    const std::string ordinal_prefix = "ordinal:";

    if (selector_lower.rfind(row_prefix, 0) == 0) {
        const std::string value = selector.substr(row_prefix.size());
        return value == cell.row_pointer ? 3 : 0;
    }
    if (selector_lower.rfind(column_prefix, 0) == 0) {
        const std::string value = selector.substr(column_prefix.size());
        return value == cell.column_pointer ? 3 : 0;
    }
    if (selector_lower.rfind(cell_prefix, 0) == 0) {
        const std::string value = selector.substr(cell_prefix.size());
        return value == cell.cell_identity_hash ? 5 : 0;
    }
    if (selector_lower.rfind(cell_pointer_prefix, 0) == 0) {
        const std::string value = selector.substr(cell_pointer_prefix.size());
        return value == cell.cell_pointer ? 5 : 0;
    }
    if (selector_lower.rfind(ordinal_prefix, 0) == 0) {
        std::uint64_t ordinal = 0;
        const std::string value = selector.substr(ordinal_prefix.size());
        return parse_u64(value, ordinal) && ordinal == cell.ordinal ? 5 : 0;
    }

    const std::string dot_selector = cell.row_pointer + "." + cell.column_pointer;
    const std::string arrow_selector = cell.row_pointer + "->" + cell.column_pointer;
    if (selector == dot_selector || selector == arrow_selector) {
        return 4;
    }

    if (selector == cell.row_pointer || selector == cell.column_pointer) {
        return 2;
    }

    return 0;
}

Rule select_rule(const std::vector<Rule>& rules, const CellRecord& cell, int& rank) {
    Rule selected{"default", "false", 0};
    int best_rank = 0;

    for (const Rule& rule : rules) {
        const int candidate_rank = selector_match_rank(rule, cell);
        if (candidate_rank == 0) {
            continue;
        }
        if (candidate_rank > best_rank ||
            (candidate_rank == best_rank && rule.order >= selected.order)) {
            selected = rule;
            best_rank = candidate_rank;
        }
    }

    rank = best_rank;
    return selected;
}

bool contains_case_insensitive(const std::string& haystack, const std::string& needle) {
    return to_lower(haystack).find(to_lower(needle)) != std::string::npos;
}

std::map<std::string, bool> make_variables(const TableSource& table,
                                           const CellRecord& cell,
                                           const IntegrityReport& report,
                                           const std::map<std::string, bool>& user_facts) {
    std::map<std::string, bool> vars = user_facts;

    const bool row_semantic_present = !trim(cell.row_semantic).empty();
    const bool column_semantic_present = !trim(cell.column_semantic).empty();
    const bool semantic_present = row_semantic_present && column_semantic_present;
    const bool hard_barrier = contains_case_insensitive(cell.barrier_policy, "hard") ||
                              equals_ignore_case(metadata_value(table, "hard_barrier", "false"), "true");
    const bool boolean_engine_is_14 = contains_case_insensitive(cell.boolean_engine, "14.cpp") ||
                                      contains_case_insensitive(metadata_value(table, "boolean_engine"), "14.cpp");

    vars["true"] = true;
    vars["false"] = false;
    vars["one"] = true;
    vars["zero"] = false;

    vars["row_known"] = report.row_known;
    vars["column_known"] = report.column_known;
    vars["row_pointer_matches"] = report.row_pointer_matches;
    vars["column_pointer_matches"] = report.column_pointer_matches;
    vars["row_hash_ok"] = report.row_hash_ok;
    vars["column_hash_ok"] = report.column_hash_ok;
    vars["row_semantic_hash_ok"] = report.row_semantic_hash_ok;
    vars["column_semantic_hash_ok"] = report.column_semantic_hash_ok;
    vars["cell_identity_ok"] = report.cell_identity_ok;
    vars["integrity_ok"] = report.integrity_ok;
    vars["semantic_present"] = semantic_present;
    vars["row_semantic_present"] = row_semantic_present;
    vars["column_semantic_present"] = column_semantic_present;
    vars["hard_barrier"] = hard_barrier;
    vars["barrier_policy_known"] = !trim(cell.barrier_policy).empty();
    vars["boolean_engine_is_14"] = boolean_engine_is_14;
    vars["contract_present"] = !trim(cell.boolean_contract).empty();
    vars["acceptance_deferred"] = contains_case_insensitive(cell.acceptance_state, "deferred");

    vars["row__" + sanitize_identifier(cell.row_pointer)] = true;
    vars["column__" + sanitize_identifier(cell.column_pointer)] = true;
    vars["cell__" + sanitize_identifier(cell.cell_identity_hash)] = true;

    return vars;
}

Decision evaluate_cell(const TableSource& table,
                       const CellRecord& cell,
                       const std::vector<Rule>& rules,
                       const std::map<std::string, bool>& user_facts,
                       bool strict) {
    Decision decision;
    decision.cell = &cell;
    decision.integrity = verify_cell(table, cell);

    if (strict && !decision.integrity.integrity_ok) {
        std::ostringstream message;
        message << "Integrity failure for cell ordinal " << cell.ordinal
                << ": expected cell hash " << decision.integrity.expected_cell_identity_hash
                << " but found " << cell.cell_identity_hash;
        throw std::runtime_error(message.str());
    }

    decision.selected_rule = select_rule(rules, cell, decision.selector_rank);
    decision.expression_hash = hex64(fnv1a_64(decision.selected_rule.expression));

    const std::map<std::string, bool> variables = make_variables(table, cell, decision.integrity, user_facts);
    BoolExpressionParser parser(decision.selected_rule.expression, variables);
    decision.expression_result = parser.evaluate();
    decision.accepted = decision.integrity.integrity_ok && decision.expression_result;

    if (decision.accepted) {
        std::ostringstream accepted;
        accepted << "accepted_information(" << cell.row_pointer << ","
                 << cell.column_pointer << "," << cell.cell_identity_hash << ")";
        decision.accepted_information = accepted.str();
    } else {
        std::ostringstream rejected;
        rejected << "barrier_rejection(" << cell.row_pointer << ","
                 << cell.column_pointer << "," << cell.cell_identity_hash << ")";
        decision.accepted_information = rejected.str();
    }

    std::ostringstream event_material;
    const char sep = static_cast<char>(0x1F);
    event_material << "14.cpp" << sep
                   << metadata_value(table, "table_name") << sep
                   << cell.ordinal << sep
                   << cell.row_index << sep
                   << cell.column_index << sep
                   << cell.row_pointer << sep
                   << cell.column_pointer << sep
                   << cell.cell_pointer << sep
                   << cell.cell_identity_hash << sep
                   << decision.selected_rule.selector << sep
                   << decision.selected_rule.expression << sep
                   << (decision.accepted ? "accepted" : "rejected") << sep
                   << decision.accepted_information;
    decision.event_hash = hex64(fnv1a_64(event_material.str()));

    return decision;
}

std::uint64_t requested_count(const Options& options, std::uint64_t total) {
    if (options.start >= total) {
        return 0;
    }
    const std::uint64_t remaining = total - options.start;
    return options.all || options.limit > remaining ? remaining : options.limit;
}

void validate_safety(const Options& options, std::uint64_t count) {
    if (!options.allow_large && count > kUnapprovedRecordLimit) {
        throw std::runtime_error("Refusing to evaluate more than 100000 cells without --allow-large.");
    }
}

void write_sample_rules(const std::string& path, bool overwrite) {
    if (!overwrite && file_exists(path)) {
        throw std::runtime_error("Sample rules already exist. Use --overwrite to replace: " + path);
    }
    FileSink sink(path, "wb");
    Writer out(sink);
    out << "# book_sport_14.rules\n"
        << "# Rules are selected by specificity. Later rules of equal specificity override earlier ones.\n"
        << "# selector=Boolean expression\n"
        << "default=false\n"
        << "column:observe=integrity_ok AND semantic_present AND boolean_engine_is_14\n"
        << "column:classify=integrity_ok AND semantic_present AND classification_authorized\n"
        << "column:validate=integrity_ok AND semantic_present AND measurement_verified\n"
        << "column:transform=integrity_ok AND semantic_present AND transform_authorized AND measurement_verified\n"
        << "column:compose=integrity_ok AND semantic_present AND composition_authorized\n"
        << "column:barrier_check=integrity_ok AND hard_barrier AND operator_authorized\n"
        << "x_boundary->transform=false\n"
        << "x_boundary->barrier_check=integrity_ok AND hard_barrier AND operator_authorized\n";
}

void write_sample_facts(const std::string& path, bool overwrite) {
    if (!overwrite && file_exists(path)) {
        throw std::runtime_error("Sample facts already exist. Use --overwrite to replace: " + path);
    }
    FileSink sink(path, "wb");
    Writer out(sink);
    out << "# book_sport_14.facts\n"
        << "# These facts are external Boolean premises supplied to the acceptance engine.\n"
        << "operator_authorized=true\n"
        << "measurement_verified=true\n"
        << "classification_authorized=true\n"
        << "transform_authorized=true\n"
        << "composition_authorized=false\n";
}

void write_header(Writer& out,
                  const Options& options,
                  const TableSource& table,
                  const std::vector<Rule>& rules,
                  const std::map<std::string, bool>& facts,
                  std::uint64_t selected_count) {
    out << "# book-sport-acceptance-source v1\n";
    out << "# source_kind=14.cpp\n";
    out << "# role=dynamic_boolean_truth_arithmetic_acceptance_engine\n";
    out << "# purpose=logical_implementation_of_accepted_information_from_static_book_sport_table\n";
    out << "# record_mode=escaped_line\n";
    out << "# table_source=" << escape_field(options.table_path) << '\n';
    out << "# table_name=" << escape_field(metadata_value(table, "table_name")) << '\n';
    out << "# static_source_kind=" << escape_field(metadata_value(table, "source_kind")) << '\n';
    out << "# boolean_contract=" << escape_field(metadata_value(table, "boolean_contract")) << '\n';
    out << "# barrier_policy=" << escape_field(metadata_value(table, "barrier_policy")) << '\n';
    out << "# hard_barrier=" << escape_field(metadata_value(table, "hard_barrier", "true")) << '\n';
    out << "# rows_loaded=" << table.rows.size() << '\n';
    out << "# columns_loaded=" << table.columns.size() << '\n';
    out << "# cells_loaded=" << table.cells.size() << '\n';
    out << "# start=" << options.start << '\n';
    out << "# selected_cells=" << selected_count << '\n';
    out << "# rules_loaded=" << rules.size() << '\n';
    out << "# facts_loaded=" << facts.size() << '\n';
    out << "# strict_integrity=" << (options.strict ? "true" : "false") << '\n';
    out << "# accepted_only=" << (options.accepted_only ? "true" : "false") << '\n';
    out << "# rejected_only=" << (options.rejected_only ? "true" : "false") << '\n';
    out << "# schema.rule=rule order selector expression_hash expression\n";
    out << "# schema.fact=fact name value\n";
    out << "# schema.event=event ordinal row_index column_index row_pointer column_pointer cell_pointer cell_identity_hash selected_rule selector_rank expression_hash boolean_result acceptance_state barrier_action integrity_ok row_hash_ok column_hash_ok row_semantic_hash_ok column_semantic_hash_ok cell_identity_ok event_hash accepted_information expression\n";

    for (const Rule& rule : rules) {
        out << "rule\t"
            << rule.order << '\t'
            << escape_field(rule.selector) << '\t'
            << hex64(fnv1a_64(rule.expression)) << '\t'
            << escape_field(rule.expression) << '\n';
    }

    for (const auto& fact : facts) {
        out << "fact\t"
            << escape_field(fact.first) << '\t'
            << (fact.second ? "true" : "false") << '\n';
    }
}

void write_decision(Writer& out, const Decision& decision) {
    const CellRecord& cell = *decision.cell;
    const std::string acceptance_state = decision.accepted ? "accepted_information" : "rejected_by_hard_barrier";
    const std::string barrier_action = decision.accepted ? "barrier_opened_by_boolean_true" : "barrier_remains_closed";

    out << "event\t"
        << cell.ordinal << '\t'
        << cell.row_index << '\t'
        << cell.column_index << '\t'
        << escape_field(cell.row_pointer) << '\t'
        << escape_field(cell.column_pointer) << '\t'
        << escape_field(cell.cell_pointer) << '\t'
        << escape_field(cell.cell_identity_hash) << '\t'
        << escape_field(decision.selected_rule.selector) << '\t'
        << decision.selector_rank << '\t'
        << decision.expression_hash << '\t'
        << (decision.expression_result ? "true" : "false") << '\t'
        << acceptance_state << '\t'
        << barrier_action << '\t'
        << (decision.integrity.integrity_ok ? "true" : "false") << '\t'
        << (decision.integrity.row_hash_ok ? "true" : "false") << '\t'
        << (decision.integrity.column_hash_ok ? "true" : "false") << '\t'
        << (decision.integrity.row_semantic_hash_ok ? "true" : "false") << '\t'
        << (decision.integrity.column_semantic_hash_ok ? "true" : "false") << '\t'
        << (decision.integrity.cell_identity_ok ? "true" : "false") << '\t'
        << decision.event_hash << '\t'
        << escape_field(decision.accepted_information) << '\t'
        << escape_field(decision.selected_rule.expression) << '\n';
}

void print_plan(const Options& options,
                const TableSource& table,
                const std::vector<Rule>& rules,
                const std::map<std::string, bool>& facts,
                std::uint64_t count) {
    std::cout
        << "14.cpp Book Sport dynamic Boolean acceptance dry run\n"
        << "  table: " << options.table_path << '\n'
        << "  table name: " << metadata_value(table, "table_name") << '\n'
        << "  rows: " << table.rows.size() << '\n'
        << "  columns: " << table.columns.size() << '\n'
        << "  cells loaded: " << table.cells.size() << '\n'
        << "  start: " << options.start << '\n'
        << "  cells selected: " << count << '\n'
        << "  rules loaded: " << rules.size() << '\n'
        << "  facts loaded: " << facts.size() << '\n'
        << "  strict integrity: " << (options.strict ? "true" : "false") << '\n'
        << "  output: " << options.output_target << '\n'
        << "  execute: false\n\n"
        << "Add --execute to emit acceptance/rejection event records.\n";
}

void run_engine(const Options& options,
                const TableSource& table,
                const std::vector<Rule>& rules,
                const std::map<std::string, bool>& facts) {
    const std::uint64_t total = static_cast<std::uint64_t>(table.cells.size());
    const std::uint64_t count = requested_count(options, total);
    validate_safety(options, count);

    if (!options.execute) {
        print_plan(options, table, rules, facts, count);
        return;
    }

    if (options.output_target == "-" || equals_ignore_case(options.output_target, "stdout")) {
        StreamSink sink(std::cout);
        Writer out(sink);
        write_header(out, options, table, rules, facts, count);
        for (std::uint64_t i = 0; i < count; ++i) {
            const CellRecord& cell = table.cells[static_cast<std::size_t>(options.start + i)];
            const Decision decision = evaluate_cell(table, cell, rules, facts, options.strict);
            if (options.accepted_only && !decision.accepted) continue;
            if (options.rejected_only && decision.accepted) continue;
            write_decision(out, decision);
        }
        return;
    }

    if (!options.overwrite && file_exists(options.output_target)) {
        throw std::runtime_error("Output file already exists. Use --overwrite to replace: " + options.output_target);
    }

    FileSink sink(options.output_target, "wb");
    Writer out(sink);
    write_header(out, options, table, rules, facts, count);

    std::uint64_t accepted = 0;
    std::uint64_t rejected = 0;
    std::uint64_t emitted = 0;

    for (std::uint64_t i = 0; i < count; ++i) {
        const CellRecord& cell = table.cells[static_cast<std::size_t>(options.start + i)];
        const Decision decision = evaluate_cell(table, cell, rules, facts, options.strict);
        if (decision.accepted) {
            ++accepted;
        } else {
            ++rejected;
        }
        if (options.accepted_only && !decision.accepted) continue;
        if (options.rejected_only && decision.accepted) continue;
        write_decision(out, decision);
        ++emitted;
    }

    std::cout << "Wrote " << emitted << " Book Sport acceptance event records to "
              << options.output_target << '\n'
              << "Accepted: " << accepted << "\n"
              << "Rejected: " << rejected << "\n";
}

void print_help(const char* executable) {
    std::cout
        << "Usage:\n"
        << "  " << executable << " --table <13.cpp table file> [--rules <path>] [--facts <path>] [--execute]\n"
        << "  " << executable << " --sample-rules <path>\n"
        << "  " << executable << " --sample-facts <path>\n\n"
        << "Input:\n"
        << "  --table <path>             static Book Sport table emitted by 13.cpp\n"
        << "  --rules <path>             Boolean acceptance rule assignments\n"
        << "  --facts <path>             Boolean premise assignments\n"
        << "  --rule <selector=expr>     add one rule directly\n"
        << "  --accept-if <expr>         shorthand for default=<expr>\n"
        << "  --fact <name=value>        add one Boolean fact directly\n\n"
        << "Selection/output:\n"
        << "  --start <n>                first cell index, default 0\n"
        << "  --limit <n>                maximum cells, default 10000\n"
        << "  --all                      evaluate all cells after --start\n"
        << "  --accepted-only            emit only accepted events\n"
        << "  --rejected-only            emit only rejected events\n"
        << "  --output-target <path>     file path, stdout, or -\n"
        << "  --execute                  actually write output\n"
        << "  --overwrite                allow replacing output files\n"
        << "  --allow-large              allow more than 100000 selected cells\n\n"
        << "Integrity:\n"
        << "  --strict                   fail closed on integrity mismatch, default\n"
        << "  --no-strict                emit rejected records instead of aborting\n\n"
        << "Samples:\n"
        << "  --sample-rules <path>      write sample rules file\n"
        << "  --sample-facts <path>      write sample facts file\n";
}

struct ParsedProgram {
    Options options;
    std::vector<Rule> direct_rules;
    std::map<std::string, bool> direct_facts;
};

ParsedProgram parse_program(int argc, char** argv) {
    ParsedProgram program;
    std::uint64_t direct_rule_order = 1000000;
    std::vector<std::string> args(argv, argv + argc);

    for (std::size_t i = 1; i < args.size(); ++i) {
        const std::string& arg = args[i];
        if (arg == "--help" || arg == "-h") {
            print_help(argv[0]);
            std::exit(0);
        } else if (arg == "--execute") {
            program.options.execute = true;
        } else if (arg == "--overwrite") {
            program.options.overwrite = true;
        } else if (arg == "--allow-large") {
            program.options.allow_large = true;
        } else if (arg == "--all") {
            program.options.all = true;
        } else if (arg == "--strict") {
            program.options.strict = true;
        } else if (arg == "--no-strict") {
            program.options.strict = false;
        } else if (arg == "--accepted-only") {
            program.options.accepted_only = true;
        } else if (arg == "--rejected-only") {
            program.options.rejected_only = true;
        } else if (arg == "--explain") {
            program.options.explain = true;
        } else if (arg == "--start") {
            program.options.start = require_u64_arg(args, i);
        } else if (arg == "--limit") {
            program.options.limit = require_u64_arg(args, i);
        } else if (arg == "--table") {
            program.options.table_path = require_string_arg(args, i);
        } else if (arg == "--output-target" || arg == "-o") {
            program.options.output_target = require_string_arg(args, i);
        } else if (arg == "--rules") {
            program.options.rules_path = require_string_arg(args, i);
        } else if (arg == "--facts") {
            program.options.facts_path = require_string_arg(args, i);
        } else if (arg == "--sample-rules") {
            program.options.sample_rules_path = require_string_arg(args, i);
        } else if (arg == "--sample-facts") {
            program.options.sample_facts_path = require_string_arg(args, i);
        } else if (arg == "--rule") {
            const auto assignment = split_assignment(require_string_arg(args, i));
            program.direct_rules.push_back({assignment.first, assignment.second, direct_rule_order++});
        } else if (arg == "--accept-if") {
            program.direct_rules.push_back({"default", require_string_arg(args, i), direct_rule_order++});
        } else if (arg == "--fact") {
            const auto assignment = split_assignment(require_string_arg(args, i));
            bool value = false;
            if (!parse_bool_value(assignment.second, value)) {
                throw std::runtime_error("Invalid direct Boolean fact: " + assignment.second);
            }
            program.direct_facts[assignment.first] = value;
            program.direct_facts[to_lower(assignment.first)] = value;
        } else {
            throw std::runtime_error("Unknown option: " + arg);
        }
    }

    if (program.options.accepted_only && program.options.rejected_only) {
        throw std::runtime_error("Use only one of --accepted-only or --rejected-only.");
    }

    return program;
}

int run(int argc, char** argv) {
    ParsedProgram program = parse_program(argc, argv);
    Options& options = program.options;

    if (!options.sample_rules_path.empty()) {
        write_sample_rules(options.sample_rules_path, options.overwrite);
        std::cout << "Wrote sample rules to " << options.sample_rules_path << '\n';
        return 0;
    }

    if (!options.sample_facts_path.empty()) {
        write_sample_facts(options.sample_facts_path, options.overwrite);
        std::cout << "Wrote sample facts to " << options.sample_facts_path << '\n';
        return 0;
    }

    if (options.table_path.empty()) {
        print_help(argv[0]);
        return 0;
    }

    TableSource table = load_table_source(options.table_path);

    std::uint64_t next_rule_order = 0;
    std::vector<Rule> rules = load_rules_file(options.rules_path, next_rule_order);
    for (const Rule& direct_rule : program.direct_rules) {
        rules.push_back(direct_rule);
    }
    if (rules.empty()) {
        rules.push_back({"default", "false", next_rule_order++});
    }

    std::map<std::string, bool> facts = load_facts_file(options.facts_path);
    for (const auto& fact : program.direct_facts) {
        facts[fact.first] = fact.second;
    }

    run_engine(options, table, rules, facts);
    return 0;
}

} // namespace

int main(int argc, char** argv) {
    try {
        return run(argc, argv);
    } catch (const std::exception& ex) {
        std::cerr << "14.cpp error: " << ex.what() << '\n';
        return 1;
    }
}

